lopee_goodbye:
    path:     /byebye-world
    defaults: { _controller: LopeePlatformBundle:Bye:index }

lopee_platform_home:
    path:      /{page}
    defaults:
        _controller: LopeePlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

lopee_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: LopeePlatformBundle:Advert:view
    requirements:
        id: \d+

lopee_platform_add:
    path:      /add
    defaults:
        _controller: LopeePlatformBundle:Advert:add

lopee_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: LopeePlatformBundle:Advert:edit
    requirements:
        id: \d+

lopee_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: LopeePlatformBundle:Advert:delete
    requirements:
        id: \d+
